package pantallas;

import Entidades.Carta;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import truco_iar.GestorTrucoL;

public class Partido extends javax.swing.JFrame {


    
    private final GestorTrucoL gestor;
    private Carta carta0;
    private Carta carta1;
    private Carta carta2;
    private int cartasJugadasIA;
    private int cartasJugadasUsr;
    private boolean cantoquerido =false;
    
    public Partido(GestorTrucoL gestor){
        initComponents();
        this.setVisible(true);        
        this.cartasJugadasIA = 0;
        this.cartasJugadasUsr = 0;
        this.gestor = gestor;   
        this.jLabelPuntajeIA.setText(Integer.toString(gestor.getJugadorHumano().getCantidadPuntos()));
        this.jLabelPuntajeUsr.setText(Integer.toString(gestor.getJugadorMaquina().getCantidadPuntos()));
    }
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        carta1usr = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        carta2usr = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        carta3usr = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        labelCarta1Usr = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        labelCarta2Usr = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        labelCarta3Usr = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        labelcarta1IA = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        labelCarta2IA = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        labelCarta3IA = new javax.swing.JLabel();
        botonSiguiente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelPuntajeIA = new javax.swing.JLabel();
        jLabelPuntajeUsr = new javax.swing.JLabel();
        cantarTrucoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sus cartas"));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(106, 143));

        carta1usr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta1usrMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carta1usr, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carta1usr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(106, 143));

        carta2usr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta2usrMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carta2usr, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carta2usr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(106, 143));

        carta3usr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carta3usrMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carta3usr, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carta3usr, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setPreferredSize(new java.awt.Dimension(106, 143));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCarta1Usr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCarta1Usr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelCarta2Usr.setMaximumSize(new java.awt.Dimension(32767, 32767));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCarta2Usr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCarta2Usr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelCarta3Usr.setMaximumSize(new java.awt.Dimension(32767, 32767));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCarta3Usr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCarta3Usr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setPreferredSize(new java.awt.Dimension(106, 143));

        labelcarta1IA.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelcarta1IA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelcarta1IA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.setPreferredSize(new java.awt.Dimension(106, 143));

        labelCarta2IA.setMaximumSize(new java.awt.Dimension(32767, 32767));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCarta2IA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCarta2IA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.setPreferredSize(new java.awt.Dimension(106, 143));

        labelCarta3IA.setMaximumSize(new java.awt.Dimension(32767, 32767));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCarta3IA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCarta3IA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        botonSiguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonSiguiente.setText("Siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 680, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Puntaje MAQUINA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 21, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Puntaje HUMANO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabelPuntajeIA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPuntajeIA.setText("jLabel5");
        jLabelPuntajeIA.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelPuntajeIAPropertyChange(evt);
            }
        });
        getContentPane().add(jLabelPuntajeIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabelPuntajeUsr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPuntajeUsr.setText("jLabel6");
        getContentPane().add(jLabelPuntajeUsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        cantarTrucoButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cantarTrucoButton.setText("Cantar truco");
        cantarTrucoButton.setFocusable(false);
        cantarTrucoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantarTrucoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cantarTrucoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallas/img/bloc-de-notas.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 310, 100));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pantallas/img/table.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        this.labelCarta1Usr.setIcon(null);
        this.labelCarta2Usr.setIcon(null);
        this.labelCarta3Usr.setIcon(null);
        this.labelcarta1IA.setIcon(null);
        this.labelCarta2IA.setIcon(null);
        this.labelCarta3IA.setIcon(null);
        if(gestor.getEstadoActualMesa().isTerminoElJuego()){
            gestor.iniciarPartida();
            this.setVisible(false);
        }else{
            gestor.iniciarMano();        
        }        
        
        
        this.cantarTrucoButton.setText("Cantar Truco");
        
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void carta1usrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta1usrMouseClicked
        if(gestor.getJugadorHumano().getMano().get(0).getNumero() == -1) return;    
        this.carta1usr.setIcon(null);
        actualizarCartas(gestor.getJugadorHumano().getMano().get(0),gestor.getEstadoActualMesa().getRondaActual(),true);
        gestor.cartaJugadaHumano(gestor.getJugadorHumano().getMano().get(0));
    }//GEN-LAST:event_carta1usrMouseClicked

    private void carta2usrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta2usrMouseClicked
        if(gestor.getJugadorHumano().getMano().get(1).getNumero() == -1) return;
        this.carta2usr.setIcon(null);
        actualizarCartas(gestor.getJugadorHumano().getMano().get(1),gestor.getEstadoActualMesa().getRondaActual(),true);
        gestor.cartaJugadaHumano(gestor.getJugadorHumano().getMano().get(1));
    }//GEN-LAST:event_carta2usrMouseClicked

    private void carta3usrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carta3usrMouseClicked
        if(gestor.getJugadorHumano().getMano().get(2).getNumero() == -1) return;
        this.carta3usr.setIcon(null);
        actualizarCartas(gestor.getJugadorHumano().getMano().get(2),gestor.getEstadoActualMesa().getRondaActual(),true);
        gestor.cartaJugadaHumano(gestor.getJugadorHumano().getMano().get(2));
    }//GEN-LAST:event_carta3usrMouseClicked

    private void jLabelPuntajeIAPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelPuntajeIAPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelPuntajeIAPropertyChange

    private void cantarTrucoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantarTrucoButtonActionPerformed
        gestor.cantoRealizado(true);
    }//GEN-LAST:event_cantarTrucoButtonActionPerformed
    
    public void actualizarPuntaje(int puntaje, Boolean esHumano){
        if(esHumano) this.jLabelPuntajeUsr.setText(Integer.toString(puntaje));
        else this.jLabelPuntajeIA.setText(Integer.toString(puntaje));        
    }

    public void habilitarBotonCanto(boolean habilitar){
        this.cantarTrucoButton.setEnabled(habilitar);
    }
    
    public void habilitarBotonSiguiente(boolean habilitar){
        this.botonSiguiente.setEnabled(habilitar);
    }
    
    public void actualizarCartas(ArrayList<Carta> cartasJugadorHumano){ 
            carta0 = cartasJugadorHumano.get(0);
            carta1 = cartasJugadorHumano.get(1);
            carta2 = cartasJugadorHumano.get(2);
            this.carta1usr.setIcon(new javax.swing.ImageIcon(getClass().getResource(carta0.getImgDir())));
            this.carta2usr.setIcon(new javax.swing.ImageIcon(getClass().getResource(carta1.getImgDir())));
            this.carta3usr.setIcon(new javax.swing.ImageIcon(getClass().getResource(carta2.getImgDir()))); 
            cartasJugadasUsr=0;
            cartasJugadasIA=0;
    }
    
    public void actualizarCartas(Carta c, int ronda, Boolean esHumano){
        if(esHumano){
            if(c == carta0){
                this.carta1usr.setIcon(null);
            }
            if(c == carta1){
                this.carta2usr.setIcon(null);
            }
            if(c == carta2){
                this.carta3usr.setIcon(null);
            }
            if(cartasJugadasUsr==0){
                this.labelCarta1Usr.setIcon(new javax.swing.ImageIcon(getClass().getResource(c.getImgDir())));
            }
            if(cartasJugadasUsr==1){
                this.labelCarta2Usr.setIcon(new javax.swing.ImageIcon(getClass().getResource(c.getImgDir())));
            }
            if(cartasJugadasUsr==2){
                this.labelCarta3Usr.setIcon(new javax.swing.ImageIcon(getClass().getResource(c.getImgDir())));
            }
            cartasJugadasUsr++;
        }
        if(!esHumano){
            if(cartasJugadasIA==0){
                this.labelcarta1IA.setIcon(new javax.swing.ImageIcon(getClass().getResource(c.getImgDir())));
            }
            if(cartasJugadasIA==1){
                this.labelCarta2IA.setIcon(new javax.swing.ImageIcon(getClass().getResource(c.getImgDir())));
            }
            if(cartasJugadasIA==2){
                this.labelCarta3IA.setIcon(new javax.swing.ImageIcon(getClass().getResource(c.getImgDir())));
            }
            cartasJugadasIA++;
        }
    }
    
    public void habilitarCartas(boolean habilitar){
        this.carta1usr.setEnabled(habilitar);
        this.carta2usr.setEnabled(habilitar);
        this.carta3usr.setEnabled(habilitar);
    }

    public JLabel getCarta1usr() {
        return carta1usr;
    }

    public JLabel getCarta2usr() {
        return carta2usr;
    }

    public JLabel getCarta3usr() {
        return carta3usr;
    }
    
        public JButton getCantarTrucoButton() {
        return cantarTrucoButton;
    }

       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton cantarTrucoButton;
    private javax.swing.JLabel carta1usr;
    private javax.swing.JLabel carta2usr;
    private javax.swing.JLabel carta3usr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPuntajeIA;
    private javax.swing.JLabel jLabelPuntajeUsr;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelCarta1Usr;
    private javax.swing.JLabel labelCarta2IA;
    private javax.swing.JLabel labelCarta2Usr;
    private javax.swing.JLabel labelCarta3IA;
    private javax.swing.JLabel labelCarta3Usr;
    private javax.swing.JLabel labelcarta1IA;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
